import Head from "next/head";
import Image from "next/image";
import client from "../apolloclient";
import { gql } from "@apollo/client";
import Footer from "../components/Footer";

export default function Home({ Images }) {
  console.log(Images); //log image object arrays to the terminal
  return (
    <div>
      <Head>
        <title>Maua</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav class="bg-white shadow dark:bg-gradient-to-r from-gray-500 to-indigo-500 min-w-100 fixed left-0 top-0 w-full z-10 ease-induration-300">
      <div class="container flex items-center justify-center p-6 mx-auto text-gray-600 capitalize dark:text-gray-300">
        <a
          href="https://www.github.com/tckiprotich"
          class="text-gray-800 transition-colors duration-300 transform dark:text-gray-200 border-b-2 border-blue-500 mx-1.5 sm:mx-6"
        >
          Github
        </a>

        <a
          href="#"
          class="border-b-2 border-transparent hover:text-gray-800 transition-colors duration-300 transform dark:hover:text-gray-200 hover:border-blue-500 mx-1.5 sm:mx-6"
        >
          Portfolio
        </a>

        {/* <a
          href="#"
          class="border-b-2 border-transparent hover:text-gray-800 transition-colors duration-300 transform dark:hover:text-gray-200 hover:border-blue-500 mx-1.5 sm:mx-6"
        >
          pricing
        </a> */}

        <a
          href="https://www.github.com/tckiprotich"
          class="border-b-2 border-transparent hover:text-gray-800 transition-colors duration-300 transform dark:hover:text-gray-200 hover:border-blue-500 mx-1.5 sm:mx-6"
        >
          blog
        </a>

        <a
          href="#"
          class="border-b-2 border-transparent hover:text-gray-800 transition-colors duration-300 transform dark:hover:text-gray-200 hover:border-blue-500 mx-1.5 sm:mx-6"
        >
          <svg
            class="w-4 h-4 fill-current"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              clip-rule="evenodd"
              d="M1 11.9554V12.0446C1.01066 14.7301 1.98363 17.1885 3.59196 19.0931C4.05715 19.6439 4.57549 20.1485 5.13908 20.5987C5.70631 21.0519 6.31937 21.4501 6.97019 21.7853C7.90271 22.2656 8.91275 22.6165 9.97659 22.8143C10.5914 22.9286 11.2243 22.9918 11.8705 22.9993C11.9136 22.9998 11.9567 23 11.9999 23C15.6894 23 18.9547 21.1836 20.9502 18.3962C21.3681 17.8125 21.7303 17.1861 22.0291 16.525C22.6528 15.1448 22.9999 13.613 22.9999 12C22.9999 8.73978 21.5816 5.81084 19.3283 3.79653C18.8064 3.32998 18.2397 2.91249 17.6355 2.55132C15.9873 1.56615 14.0597 1 11.9999 1C11.888 1 11.7764 1.00167 11.6653 1.00499C9.99846 1.05479 8.42477 1.47541 7.0239 2.18719C6.07085 2.67144 5.19779 3.29045 4.42982 4.01914C3.7166 4.69587 3.09401 5.4672 2.58216 6.31302C2.22108 6.90969 1.91511 7.54343 1.6713 8.20718C1.24184 9.37631 1.00523 10.6386 1 11.9554ZM20.4812 15.0186C20.8171 14.075 20.9999 13.0588 20.9999 12C20.9999 9.54265 20.0151 7.31533 18.4186 5.6912C17.5975 7.05399 16.5148 8.18424 15.2668 9.0469C15.7351 10.2626 15.9886 11.5603 16.0045 12.8778C16.7692 13.0484 17.5274 13.304 18.2669 13.6488C19.0741 14.0252 19.8141 14.487 20.4812 15.0186ZM15.8413 14.8954C16.3752 15.0321 16.904 15.22 17.4217 15.4614C18.222 15.8346 18.9417 16.3105 19.5723 16.8661C18.0688 19.2008 15.5151 20.7953 12.5788 20.9817C13.5517 20.0585 14.3709 18.9405 14.972 17.6514C15.3909 16.7531 15.678 15.8272 15.8413 14.8954ZM13.9964 12.6219C13.9583 11.7382 13.7898 10.8684 13.5013 10.0408C10.6887 11.2998 7.36584 11.3765 4.35382 9.97197C4.01251 9.81281 3.68319 9.63837 3.36632 9.44983C3.12787 10.2584 2.99991 11.1142 2.99991 12C2.99991 13.9462 3.61763 15.748 4.6677 17.2203C6.83038 14.1875 10.3685 12.4987 13.9964 12.6219ZM6.047 18.7502C7.77258 16.059 10.7714 14.5382 13.8585 14.6191C13.723 15.3586 13.4919 16.093 13.1594 16.8062C12.3777 18.4825 11.1453 19.805 9.67385 20.6965C8.31043 20.3328 7.07441 19.6569 6.047 18.7502ZM11.9999 3C13.7846 3 15.4479 3.51946 16.847 4.41543C16.2113 5.54838 15.3593 6.4961 14.368 7.23057C13.3472 5.57072 11.8752 4.16433 10.027 3.21692C10.6619 3.07492 11.3222 3 11.9999 3ZM8.80619 4.84582C10.4462 5.61056 11.7474 6.80659 12.6379 8.23588C10.3464 9.24654 7.64722 9.30095 5.19906 8.15936C4.83384 7.98905 4.48541 7.79735 4.15458 7.58645C4.91365 6.24006 6.00929 5.10867 7.32734 4.30645C7.82672 4.44058 8.32138 4.61975 8.80619 4.84582Z"
              fill="currentColor"
            />
          </svg>
        </a>

        <a
          href="#"
          class="border-b-2 border-transparent hover:text-gray-800 transition-colors duration-300 transform dark:hover:text-gray-200 hover:border-blue-500 mx-1.5 sm:mx-6"
        >
          <svg
            class="w-5 h-5 fill-current"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="m.75 19h7.092c4.552 0 6.131-6.037 2.107-8.203 2.701-2.354 1.029-6.797-2.595-6.797h-6.604c-.414 0-.75.336-.75.75v13.5c0 .414.336.75.75.75zm.75-13.5h5.854c3.211 0 3.215 4.768 0 4.768h-5.854zm0 6.268h6.342c3.861 0 3.861 5.732 0 5.732h-6.342z" />
            <path d="m18.374 7.857c-3.259 0-5.755 2.888-5.635 5.159-.247 3.28 2.397 5.984 5.635 5.984 2.012 0 3.888-1.065 4.895-2.781.503-.857-.791-1.613-1.293-.76-.739 1.259-2.12 2.041-3.602 2.041-2.187 0-3.965-1.668-4.125-3.771 1.443.017 4.136-.188 8.987-.033.016 0 .027-.008.042-.008 2-.09-.189-5.831-4.904-5.831zm-3.928 4.298c1.286-3.789 6.718-3.676 7.89.064-4.064.097-6.496-.066-7.89-.064z" />
            <path d="m21.308 6.464c.993 0 .992-1.5 0-1.5h-5.87c-.993 0-.992 1.5 0 1.5z" />
          </svg>
        </a>
      </div>
    </nav>

      <div className="flex items-center justify-center h-screen mb-0 bg-fixed bg-center bg-cover custom-img ">
        <div className="h-screen absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[2]" />
        <div>
          <h1 className="text-5xl text-green-600  font-bold text-center justify-center mt-7-30 ">
            Flowers bring color<br></br> to your world
          </h1>
          <p className="pt-20  text-2xl  text-center w-500 mx-20">
            A flower’s appeal is in its contradictions — so delicate in form yet
            strong in fragrance, so small in size yet big in beauty, so short in
            life yet long on effect
          </p>
        </div>
       
        
       
      </div>
      <div>
      
      <section className="bg-white dark:bg-gray-900 ">
      <div className=" mx-auto w-full max-w-md px-8 py-4 mt-16 bg-white rounded-lg shadow-lg dark:bg-gray-800">
        <div className="flex justify-center -mt-16 md:justify-end">
          
          <div className='object-cover w-20 h-20 border-2 border-blue-500 rounded-full dark:border-blue-400 custom-i'/>
        </div>

        <h2 className="mt-2 text-2xl font-semibold text-gray-800 dark:text-white md:mt-0 md:text-3xl">
          Why flowers
        </h2>

        <p className="mt-2 text-gray-600 dark:text-gray-200">
          
          Plain and simple, flowers are beautiful and give feelings of hope,
          love, vibrancy, life, the joy of spring and so much more. The range
          and contrast of colors in flowers lead to wonderful shots. When I
          decide to take a picture of a flower, I usually have to be in the
          right place at the right time. The flower has to be in bloom, and I
          have to be able to get close enough without trampling on it.
        </p>

        <div className="flex justify-end mt-4">
          <a
            href="#"
            className="text-xl font-medium text-blue-600 dark:text-blue-300"
            tabindex="0"
            role="link"
          >
            collins Tonui
          </a>
        </div>
      </div>
        <div className="container px-6 py-10 mx-auto">
          <h1 className="text-3xl font-semibold text-center text-gray-800 capitalize lg:text-4xl dark:text-white">
            Enjoy beatufiful pictures
          </h1>
          
            <div className="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 md:grid-cols-2 xl:grid-cols-3">
            {Images.images.map(({ id, name, description, img }) => (
              
              <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-gray-800/60 group-hover:opacity-100">
                <Image src={img.url} alt={name} objectfit="cover" layout="fill" width={500} height={700} />
                
                <div
                  key={id}
                  className="flex flex-col justify-center mx-auto px-8 py-4 transition-opacity duration-700 opacity-0 backdrop-blur-sm bg-gray-800/60 group-hover:opacity-100">
                
                  {/* <h2 className="mt-4 text-2xl font-semibold text-white capitalize">
                    {name}
                  </h2> */}
                  {/* <p className="mt-2 text-lg tracking-wider text-blue-400 uppercase ">
                    {description.text}
                  </p> */}
                </div>
              </div>
              ))}
            </div>
          
        </div>
      </section>
      <Footer/>
    </div>
    </div>
  );
}

//client side rendering function
export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      {
        images {
          id
          name
          description {
            text
          }
          img {
            url
          }
        }
      }
    `,
  });
  const Images = data;
  return {
    props: {
      Images,
    },
    revalidate: 10,
  };
}
